# Generated by Django 6.0.5 on 2026-06-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leave_balance',
            field=models.IntegerField(default=24),
        ),
    ]
