# Generated by Django 6.0.5 on 2026-06-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_leave_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(default='IT', max_length=100),
        ),
    ]
