# Generated by Django 6.0.5 on 2026-06-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Sick', 'Sick'), ('WFH', 'Work From Home')], default='Casual', max_length=20),
        ),
    ]
