# Generated by Django 6.0.5 on 2026-06-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_leave_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='admin_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
